# Generated by Django 4.0.4 on 2023-01-04 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('thumbnails', models.ImageField(upload_to='project_thumbnails')),
                ('live_url', models.URLField()),
                ('github_repo', models.URLField()),
                ('client', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_portfolio.projectcategory')),
                ('tools', models.ManyToManyField(to='my_portfolio.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
