# Generated by Django 4.0.4 on 2023-01-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0002_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
