# Generated by Django 4.0.4 on 2023-01-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0003_alter_portfolio_options_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
