# Generated by Django 4.0.4 on 2023-01-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0004_alter_projectcategory_name_alter_tool_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='image',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
