# Generated by Django 4.0.4 on 2023-01-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0007_alter_portfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='client image'),
        ),
    ]
