# Generated by Django 4.0.4 on 2023-01-11 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0012_alter_summary_options_summary_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnails',
        ),
        migrations.CreateModel(
            name='ProjectThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_thumbnails')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_portfolio.project')),
            ],
        ),
    ]
