# Generated by Django 4.0.4 on 2023-01-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0013_remove_project_thumbnails_projectthumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_portfolio.projectcategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(default='Personal', max_length=50),
        ),
    ]
