# Generated by Django 4.0.4 on 2023-01-11 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0014_alter_project_category_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectthumbnail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectthumbnail', to='my_portfolio.project'),
        ),
    ]
