# Generated by Django 4.0.4 on 2023-01-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0017_alter_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
