# Generated by Django 4.0.4 on 2023-08-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0019_portfolio_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
