# Generated by Django 5.2.6 on 2025-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0022_remove_project_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(default='Backend Developer', max_length=50),
        ),
    ]
