# Generated by Django 5.2.6 on 2025-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio', '0023_project_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.TextField(),
        ),
    ]
